<?php
/**
 * Created by PhpStorm.
 * User: jimmehWhy
 * Date: 30/3/2017
 * Time: 4:53 PM
 */

namespace AppBundle\Tests\Controller;
//NOTE phpunit should be used to test component features, so shouldn't need
//fixtures, but incase it does...

use Liip\FunctionalTestBundle\Test\WebTestCase;

class FixturesControllerTest extends WebTestCase
{
    public function setUp() {
        $classes =
            array(
                'AppBundle\DataFixtures\ORM\AppFixtures',
            );

        $this->loadFixtures($classes);
    }

    public function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        //code to remove
    }

    public function testThanFixturesLoadTest(){
        $this->assertTrue(true);
    }
}